### ISSUE TITLE
bam-to-emase

### ISSUE THREAD

**Issue by pranithavangala** [churchill-lab/emase#11]
Hi Im getting the below error 

bam-to-emase -a R10-HN-L2_S10_R1.sorted..bam -i ../diploid/Hawaiian_WS230.info -s Hawaiian,N2 -o R10-HN-L2_S10_R1.bowtie.transcriptome.h5
Traceback (most recent call last):
  File "/home/pv84w/.conda/envs/emase/bin/bam-to-emase", line 4, in <module>
    __import__('pkg_resources').run_script('emase==0.10.16', 'bam-to-emase')
  File "/home/pv84w/.conda/envs/emase/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pv84w/.conda/envs/emase/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/home/pv84w/.conda/envs/emase/lib/python2.7/site-packages/emase-0.10.16-py2.7.egg-info/scripts/bam-to-emase", line 109, in <module>
    sys.exit(main())
  File "/home/pv84w/.conda/envs/emase/lib/python2.7/site-packages/emase-0.10.16-py2.7.egg-info/scripts/bam-to-emase", line 95, in main
    alignmat_factory.prepare(haplotypes, loci, outdir=os.path.dirname(outfile))
  File "/home/pv84w/.conda/envs/emase/lib/python2.7/site-packages/emase/AlignmentMatrixFactory.py", line 48, in prepare
    locus, hap = fh.getrname(aln.tid).split(delim)
ValueError: too many values to unpack

Can you please help

**Comment by ptranvan** [comment]
I have the same issue. did you found a solution ?
